### ISSUE TITLE
Path queries are case-insensitive

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1165]
I have two albums with the same name except for 1 difference: 

/media/bb/audio/jazz/Sinatra/In the Wee Wee Hours
/media/bb/adio/jazz/Sinatra/In The Wee Wee Hours

the difference is just a lowercase/uppercase (t/T)

when using the command
beet rm /media/bb/audio:jazz/Sinatra/In the Wee Wee Hours (or The Wee Wee)
beet asks me if I want to delete both of the albums
I checked and even with 
beet ls /media/bb/audio:jazz/Sinatra/In the Wee Wee Hours (or The Wee Wee)
I get both the albums.

Should beet not differentiate between lower/uppercase?

**Comment by brunal** [comment]
Given that paths on Windows are case-insensitive, what happens to the problem? Is just 1 directory used? I think that platform has to be taken into consideration for the solution, since the current behaviour may be the right one there.

So the solution would be the case_sentive_like pragma on unix platforms. Where if not in `dbcore`? In `library`, as a side effect of the presence of a `PathQuery`?

**Comment by sampsyo** [comment]
Hmm, good question. I would love to avoid a global switch altogether and use something local to the query, which should make things more intelligible and more testable, but I don't currently see a way to do that.

**Comment by brunal** [comment]
A solution could be using [instr() function](http://www.sqlite.org/lang_corefunc.html#instr) instead of `LIKE` on UNIX platforms, and keeping `LIKE` for Windows.
