### ISSUE TITLE
Support for multiple instances

### ISSUE THREAD

**Issue by plgod** [sampsyo/beets#1410]
I'm wondering how (if) beets handles several instances running at the same time, and I don't really want to risk messing up my library by trying.

1. If I start an import from one ssh session and an automatic script starts another import while the first is still running, what happens? Will both tasks complete successfully by each accessing the database while the other isn't? Will the second wait for the first to finish? Will the second fail to start (lockfile, for example)? Will it corrupt the database?

2. What if the two instances try to import the same folder? I am thinking of making a script that automatically starts the beets importer on a directory whenever I drop one or more files in that directory. If I move an album into that directory, then move a second one there before the first is processed, what is the expected behaviour?

3. Last question : if I call "beet import /some/directory" and add files to that directory during the import, will they be imported?

Thanks a lot!

(Sorry I don't know how to mark this as "Discussion" instead of "Issue")

**Comment by sampsyo** [comment]
Here's the deal: most parallel operations should work most of the time, since beets uses transactions to modify the database atomically. But a few strange things might happen when multiple imports run simultaneously since the import process can be deceptively complex.

On question 1: That should probably work fine. As long as you're not importing the same music, or different copies of the same album (i.e., duplicate detection doesn't get enabled), everything should work as expected. The database will definitely not get corrupted, at least, and the two will not be sequentialized (one will not have to wait for the other to completely finish).

For the other two questions, it's worth noting that beets reads all the files up front and then begins importing them. So after an import has started, moving a new album into the directory should do nothing—it will be ignored.

**Comment by plgod** [comment]
Thanks for the quick reply!
Then the best option if there's a chance more files will be added to the directory during import is to make my script check and wait for the first beets instance to finish, since starting the import a second time on the same directory might create duplicates (or generate an error when the second instance tries to access the first files after the first instance finished and moved them out of the directory). Did I understand correctly?

**Comment by sampsyo** [comment]
Yes, like that—sounds great. You could also use incremental mode and then (hopefully) not worry about creating duplicates when you import the same container directory twice.
