### ISSUE TITLE
Beets Truck Factor

### ISSUE THREAD

**Issue by gavelino** [sampsyo/beets#1563]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Beets** and obtained a value of **2**.

The developers responsible for this TF are:

Adrian Sampson - author of 64% of the files
Bruno Cauet - author of 27% of the files

To validate our results, we would like to ask **Beets** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Beets**?

(b) Do you agree that **Beets** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Beets** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by sampsyo** [comment]
Interesting SE work.

(a) That's hard to say. I would agree that I am a main developer of beets, but it's sort of hard to define exactly who else is. @brunal has contributed a lot lately, but so have 4 or 5 others. Specifically, @brunal has done some awesome refactoring work with a particularly high count of changed lines.
(b) Things would definitely change if I disappeared. Since it's so widely used, though, I'd like to imagine that someone else could step up as maintainer.
(c) We do have lots of documentation. It also helps that many people have written plugins for beets, which means they're already familiar with its architecture.

I would of course love it if we could be even more pluralistic! I confess that I review and merge most of the PRs, even though we have a healthy level of contribution. I also do the periodic releases. As always, I would love to hear feedback about how people could be even more involved.

**Comment by gavelino** [comment]
Thank you.
