### ISSUE TITLE
badfiles gives SyntaxError: Non-ASCII character '\xc3' in file

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1722]
I did a fresh install with 

    sudo python2.7 -m pip install -e git+https://github.com/sampsyo/beets#egg=beets

and I get 
``
 ** error loading plugin badfiles:
Traceback (most recent call last):
  File "/home/jmw/Documents/src/beets/beets/plugins.py", line 254, in load_plugins
    namespace = __import__(modname, None, None)
  File "/home/jmw/Documents/src/beets/beetsplug/badfiles.py", line 2
SyntaxError: Non-ASCII character '\xc3' in file /home/jmw/Documents/src/beets/beetsplug/badfiles.py on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
``

Now I know its is the ``ç`` in François but  should that happen out of the box?  Is that a problem on my side?

**Comment by pkess** [comment]
Hi,
i think the problem is the general missing definition for the file encoding. I opened a branch [fix_encoding](https://github.com/pkess/beets/tree/fix_encoding). Would you like to check if the problem is still present with this modification?

@sampsyo: What will be our preferred way to define encoding in files? I would start to refactor all other files if we can decide which way is the best

**Comment by sampsyo** [comment]
Yes, we definitely need that encoding declaration! @pkess, feel free to merge that commit into master. I'm not sure how we never noticed this before.

I believe this comment format is the standard way. (Or maybe there's an alternative I'm not aware of?) I don't think we need to put an encoding declaration on *every* file, but we should probably do it the same way for any file that needs it (because of non-ASCII characters).

**Comment by pkess** [comment]
@jmwatte: could you try to install with the fixed version again?
