### ISSUE TITLE
^ operator problems?

### ISSUE THREAD

**Issue by jmwatte** [sampsyo/beets#1739]
this

    beet ls -a beatles  

gives( sample )

```
The Beatles - Ticket to Ride
The Beatles - We Can Work It Out / Day Tripper
The Beatles - With The Beatles
The Beatles - With The Beatles
The Beatles - Yellow Submarine
The Beatles - Yellow Submarine / Eleanor Rigby
The Beatles - Let It Be... Naked
The Beatles - The Beatles (The White Album) (Mono Vinyl 2LP)
The Beatles - The Beatles (The White Album) (Mono Vinyl 2LP)
The Beatles - The Beatles 1
The Beatles - The White Album
The Beatles - The White Album
Various - Beatles vs. Stones: British Pop Hits Go Groovy
```
 
this

    $ beet ls -a beatles album:white

gives

```
The Beatles - The Beatles (The White Album) (Mono Vinyl 2LP)
The Beatles - The Beatles (The White Album) (Mono Vinyl 2LP)
The Beatles - The White Album
The Beatles - The White Album
```

this

    $ beet ls -a beatles ^album:white

gives nothing ....
Other combinations also give nothing.
So question is : anyone else has this behaviour? Am I doing something wrong?

27/11/2015/13:00 downloaded the latest from git 1.3.16 ;no plugins loaded ;shell is zsh

grtz
jmw

**Comment by diego-plan9** [comment]
Thanks for reporting - after some testing, I can't reproduce it under my setup (using latest git, but GNU `bash` instead of `zsh`), but I'm wondering if it is due to [the way zsh handles the `^` character](http://stackoverflow.com/questions/6091827/git-show-head-doesnt-seem-to-be-working-is-this-normal/6091843#6091843).

Could you please try if using the alternative `-` operator produces the right results? Ie.:
```
$ beet ls -a -- beatles -album:white
```
If it does indeed produce the right results, it would also be great if you could try using the `^` operator but escaping it.

**Comment by jmwatte** [comment]
That did the trick  so -- and the -  and also  '^'  with or without -- dit it.
thx
jm

**Comment by sampsyo** [comment]
How about that! Looks like the zsh extended glob big syntax *also* chose ^ for negation, independently. Too bad for us, but I think we'll need to live with it.
