### ISSUE TITLE
Documentation: missing global config options - on purpose?

### ISSUE THREAD

**Issue by diego-plan9** [sampsyo/beets#1746]
By pure chance while taking a look at `library.py`, I noticed that there is a global config variable (`time_format`) being used but not present on `config.rst`. This variable was introduced a while ago in 4904106a72ba97a4aecbd0d58d75e9234436ea3e, and I'm wondering if it was not documented on purpose or perhaps an entry should be added to the documentation.

This finding also resulted in some (incomplete and far from exhaustive) *grepping*, which suggests that the following variables are also defined in `config_default.yaml` and used in the code, but currently not mentioned on the docs: `path_sep_replace`, `timeout`,  (the three of them mentioned on changelog, though), `statefile`, `verbose`. While some of them seem to fall on the "not to be messed with" category, would it be a good idea to take the time to document them for sake or completion, and try to find out if other config options on other sections suffer from the same?

**Comment by sampsyo** [comment]
Yes, these are intentionally undocumented (more or less). They fall into two categories: (1) it is probably a bad idea to change them, since you can get yourself into trouble (as with `path_sep_replace`), or (2) the option isn't very useful for end users, so the documentation omits them for concision (as with `time_format`).

The idea with these options, especially the latter category, is that it's a good policy to put the value in the configuration instead of making it a magic number or a `PYTHON_CONSTANT` regardless of whether you want it to be actually configurable.
- You avoid drudgery in the future in unforeseen circumstances that make you want to turn it into an exposed configuration knob.
- You make it clear in the code that you chose an arbitrary value rather than the "one true value" for the variable.
- Advanced users that need to make weird, unanticipated changes can do so without actually modifying the code.

So I would love to keep a policy in place where it's OK to have (and add new!) undocumented configuration options. But certainly, if any of these needs to get publicized, let's document them!

**Comment by diego-plan9** [comment]
Thanks for the detailed explanation of the rationale behind it - it sounds like a very reasonable policy, and one I'd be more than happy to adhere to. I was just trying to make sure that it was the case, and personally won't push for having any of the mentioned variables documented - feel free to close the issue if there is no real "demand" for the changes.

**Comment by sampsyo** [comment]
Great. Let's make this the current "unofficial policy" then and re-evaluate if anything comes up.
