### ISSUE TITLE
lyrics: Handle JSON decode errors

### ISSUE THREAD

**Issue by Horla** [sampsyo/beets#1770]
It worked fine few days ago. Now I get this: 
http://pastebin.com/Ni1y4DB3
http://pastebin.com/hsYMucKK

Disabling the lyrics plugin solves the problem.

**Comment by sampsyo** [comment]
Thanks for the report. I'll propose a fix soon (today, probably).

**Comment by sampsyo** [comment]
It looks like the API we use to fetch lyrics via Genius was down, and we had insufficient error handling. I added the error handling and also disabled the backend by default—since it was just causing (long) delays without returning any lyrics. We can re-enable it if the API comes back up.

https://twitter.com/b33ts/status/681633511858548737
