### ISSUE TITLE
Further documentation on queryparse.py

### ISSUE THREAD

**Issue by JesseWeinstein** [sampsyo/beets#1794]
I noticed that `beets/dbcore/queryparse.py` has 97% test coverage -- the only thing missing are lines 118-121, inside `construct_query_part`. Looking into it, those lines are only exercised when `parse_query_part` returns a `key` of `None` and a `query_class` that isn't a subclass of `FieldQuery`. `parse_query_part`'s documentation says it always returns `FieldQuery` subclasses -- but that might be in error.

I wasn't (yet) able to understand the overall logic of `queryparse.py` well enough to figure out what the purpose of the un-tested lines was, or how things flowed through. So after discussion on IRC, @sampsyo asked me to make an issue to remind him to write up more documentation on this area of the code.

**Comment by sampsyo** [comment]
OK, I added a bunch of detail to the docstrings of those two functions. Let me know if you have more questions and I'll keep expanding that.

Here's what I think is going on with your original inquiry: back when our field system wasn't as powerful, and you couldn't have `FieldQuery`s over computed fields, we needed a way to have a prefix indicate special kinds of queries. We needed a `SingletonQuery`, for example, that would check for `album_id` to be null. Now we just have a `singleton` field that can be queried in a totally normal way. I seem to recall that `PathQuery` at some point also didn't inherit from `FieldQuery` because it was hard-wired to look at the `path` field.

So I think we don't need that branch. BUT! I could be totally wrong! A little grepping doesn't reveal any interesting queries that don't inherit from `FieldQuery`, but I could be missing something. Maybe looking in the git history for when this logic was added will reveal the real reason it was there, and then we can decide whether that reason is out of date.
